GRANT ALL PRIVILEGES ON DATABASE demoDB TO usr;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO usr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO usr;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO usr;